#include <windows.h>
#include <shellapi.h>
#include <algorithm>
#include <cwchar>
#include <string>
#include <vector>

namespace {
constexpr wchar_t APP[]=L"dwrean DeskPins",MAINCLS[]=L"DwreanDeskPinsMain",SELCLS[]=L"DwreanDeskPinsSelector",MARKCLS[]=L"DwreanDeskPinsMarker",RUNNAME[]=L"dwrean-deskpins",MUTEXNAME[]=L"Local\\dwrean-deskpins-v2-single-instance";
constexpr UINT WM_TRAY=WM_APP+1,WM_PICKED=WM_APP+2,TRAYID=1,IDM_PICK=100,IDM_UNPINALL=101,IDM_STARTUP=102,IDM_ABOUT=103,IDM_EXIT=104,IDM_PINBASE=1000;
constexpr int HOTKEYID=1,IDI_APP=101,MARKSZ=28,MARKX=10,MARKY=6; constexpr UINT_PTR TIMID=1; constexpr UINT TIMMS=200;
struct Pin{HWND target=nullptr;HWND mark=nullptr;};
HINSTANCE gInst=nullptr; HWND gMain=nullptr,gSel=nullptr; HICON gIcon=nullptr; NOTIFYICONDATAW gTray{}; std::vector<Pin> gPins; POINT gPick{}; bool gSelecting=false;

std::wstring exePath(){std::wstring p(MAX_PATH,L'\0'); DWORD n=GetModuleFileNameW(nullptr,p.data(),(DWORD)p.size()); if(!n) return {}; p.resize(n); return p;}
bool startupOn(){HKEY k=nullptr; if(RegOpenKeyExW(HKEY_CURRENT_USER,L"Software\\Microsoft\\Windows\\CurrentVersion\\Run",0,KEY_QUERY_VALUE,&k)!=ERROR_SUCCESS) return false; wchar_t v[32768]{}; DWORD t=0,b=sizeof(v); LONG r=RegQueryValueExW(k,RUNNAME,nullptr,&t,(LPBYTE)v,&b); RegCloseKey(k); if(r!=ERROR_SUCCESS||t!=REG_SZ) return false; auto p=exePath(); return !p.empty()&&std::wstring(v).find(p)!=std::wstring::npos;}
bool setStartup(bool on){HKEY k=nullptr; if(RegCreateKeyExW(HKEY_CURRENT_USER,L"Software\\Microsoft\\Windows\\CurrentVersion\\Run",0,nullptr,0,KEY_SET_VALUE,nullptr,&k,nullptr)!=ERROR_SUCCESS) return false; LONG r=ERROR_SUCCESS; if(on){auto p=exePath(); if(p.empty()){RegCloseKey(k); return false;} std::wstring cmd=L"\""+p+L"\""; r=RegSetValueExW(k,RUNNAME,0,REG_SZ,(const BYTE*)cmd.c_str(),(DWORD)((cmd.size()+1)*sizeof(wchar_t)));} else {r=RegDeleteValueW(k,RUNNAME); if(r==ERROR_FILE_NOT_FOUND) r=ERROR_SUCCESS;} RegCloseKey(k); return r==ERROR_SUCCESS;}
bool topMost(HWND w){return w&&IsWindow(w)&&(GetWindowLongPtrW(w,GWL_EXSTYLE)&WS_EX_TOPMOST)!=0;}
bool ours(HWND w){return w==gMain||w==gSel;}
HWND norm(HWND w){if(!w) return nullptr; HWND r=GetAncestor(w,GA_ROOT); if(r) w=r; if(!w||!IsWindow(w)||ours(w)||w==GetDesktopWindow()||w==GetShellWindow()) return nullptr; return w;}
Pin* findPin(HWND w){for(auto &p:gPins) if(p.target==w) return &p; return nullptr;}
void destroyMark(HWND w){if(w&&IsWindow(w)) DestroyWindow(w);} 
void updateTip(){if(!gTray.hWnd) return; wchar_t tip[128]{}; swprintf_s(tip,L"dwrean DeskPins - %zu καρφιτσωμένα",gPins.size()); wcsncpy_s(gTray.szTip,tip,_TRUNCATE); gTray.uFlags=NIF_TIP; Shell_NotifyIconW(NIM_MODIFY,&gTray);} 
void placeMark(Pin& p){if(!p.mark||!IsWindow(p.mark)) return; if(!p.target||!IsWindow(p.target)||IsIconic(p.target)||!IsWindowVisible(p.target)){ShowWindow(p.mark,SW_HIDE); return;} RECT r{}; if(!GetWindowRect(p.target,&r)){ShowWindow(p.mark,SW_HIDE); return;} SetWindowPos(p.mark,HWND_TOPMOST,r.right-MARKSZ-MARKX,r.top+MARKY,MARKSZ,MARKSZ,SWP_NOACTIVATE|SWP_SHOWWINDOW);} 
void prune(){for(auto it=gPins.begin();it!=gPins.end();){if(!IsWindow(it->target)||!topMost(it->target)){destroyMark(it->mark); it=gPins.erase(it);} else ++it;} updateTip();}
void refreshMarks(){prune(); for(auto &p:gPins) placeMark(p);} 
std::wstring titleOf(HWND w){int n=GetWindowTextLengthW(w); if(n>0){std::wstring s((size_t)n+1,L'\0'); n=GetWindowTextW(w,s.data(),(int)s.size()); if(n>0){s.resize(n); return s;}} wchar_t c[128]{}; if(GetClassNameW(w,c,128)>0) return c; return L"Χωρίς τίτλο";}
std::wstring shortTitle(const std::wstring& s){return s.size()<=55?s:s.substr(0,52)+L"...";}
HWND makeMark(HWND target){HWND w=CreateWindowExW(WS_EX_TOPMOST|WS_EX_TOOLWINDOW|WS_EX_LAYERED|WS_EX_TRANSPARENT,MARKCLS,L"",WS_POPUP,0,0,MARKSZ,MARKSZ,nullptr,nullptr,gInst,nullptr); if(w) SetLayeredWindowAttributes(w,RGB(255,0,255),0,LWA_COLORKEY); return w;}
void setPinned(HWND w,bool on){w=norm(w); if(!w){MessageBeep(MB_ICONWARNING); return;} if(!SetWindowPos(w,on?HWND_TOPMOST:HWND_NOTOPMOST,0,0,0,0,SWP_NOMOVE|SWP_NOSIZE|SWP_NOACTIVATE)){MessageBeep(MB_ICONWARNING); return;} Pin* p=findPin(w); if(on){ if(!p){ Pin np; np.target=w; np.mark=makeMark(w); gPins.push_back(np); p=&gPins.back(); } if(p) placeMark(*p);} else if(p){ destroyMark(p->mark); gPins.erase(std::remove_if(gPins.begin(),gPins.end(),[&](const Pin& x){return x.target==w;}),gPins.end()); } updateTip(); }
void togglePinned(HWND w){w=norm(w); if(!w){MessageBeep(MB_ICONWARNING); return;} setPinned(w,!topMost(w));}
void unpinAll(){auto pins=gPins; for(auto &p:pins){ if(IsWindow(p.target)) SetWindowPos(p.target,HWND_NOTOPMOST,0,0,0,0,SWP_NOMOVE|SWP_NOSIZE|SWP_NOACTIVATE); destroyMark(p.mark);} gPins.clear(); updateTip();}
void cancelSelect(){if(!gSelecting) return; gSelecting=false; ReleaseCapture(); ShowWindow(gSel,SW_HIDE);} 
void beginSelect(){if(gSelecting||!gSel) return; gSelecting=true; SetWindowPos(gSel,HWND_TOPMOST,GetSystemMetrics(SM_XVIRTUALSCREEN),GetSystemMetrics(SM_YVIRTUALSCREEN),GetSystemMetrics(SM_CXVIRTUALSCREEN),GetSystemMetrics(SM_CYVIRTUALSCREEN),SWP_SHOWWINDOW); SetForegroundWindow(gSel); SetFocus(gSel); SetCapture(gSel); SetCursor(LoadCursorW(nullptr,IDC_CROSS));}
void finishSelect(){HWND t=norm(WindowFromPoint(gPick)); if(t) togglePinned(t); else MessageBeep(MB_ICONWARNING);} 
void about(){MessageBoxW(nullptr,L"dwrean DeskPins 2.1 Beta\n\nΜια εκσυγχρονισμένη έκδοση του DeskPins για σύγχρονα Windows.\n\nΑριστερό κλικ στο εικονίδιο για επιλογή παραθύρου.\nCtrl+Alt+P για καρφίτσωμα ή ξεκαρφίτσωμα του ενεργού παραθύρου.\n\nΑρχικό DeskPins: Elias Fotinis.\nΕκσυγχρονισμός: dwrean.net.",APP,MB_OK|MB_ICONINFORMATION);} 
void handleCmd(UINT id){ if(id>=IDM_PINBASE&&id<IDM_PINBASE+100){prune(); size_t i=id-IDM_PINBASE; if(i<gPins.size()) setPinned(gPins[i].target,false); return;} switch(id){case IDM_PICK: beginSelect(); break; case IDM_UNPINALL: unpinAll(); break; case IDM_STARTUP: if(!setStartup(!startupOn())) MessageBoxW(nullptr,L"Δεν ήταν δυνατή η ενημέρωση της εκκίνησης με τα Windows.",APP,MB_OK|MB_ICONERROR); break; case IDM_ABOUT: about(); break; case IDM_EXIT: PostMessageW(gMain,WM_CLOSE,0,0); break;}}
void showMenu(){prune(); HMENU m=CreatePopupMenu(), pm=CreatePopupMenu(); if(!m||!pm){if(pm)DestroyMenu(pm); if(m)DestroyMenu(m); return;} AppendMenuW(m,MF_STRING,IDM_PICK,L"Καρφίτσωμα / ξεκαρφίτσωμα παραθύρου..."); AppendMenuW(m,MF_SEPARATOR,0,nullptr); if(gPins.empty()) AppendMenuW(pm,MF_STRING|MF_GRAYED,0,L"Δεν υπάρχουν καρφιτσωμένα παράθυρα"); else for(size_t i=0;i<std::min<size_t>(gPins.size(),100);++i) AppendMenuW(pm,MF_STRING,IDM_PINBASE+(UINT)i,shortTitle(titleOf(gPins[i].target)).c_str()); AppendMenuW(m,MF_POPUP,(UINT_PTR)pm,L"Καρφιτσωμένα παράθυρα"); AppendMenuW(m,MF_STRING|(gPins.empty()?MF_GRAYED:MF_ENABLED),IDM_UNPINALL,L"Ξεκαρφίτσωμα όλων"); AppendMenuW(m,MF_SEPARATOR,0,nullptr); AppendMenuW(m,MF_STRING|(startupOn()?MF_CHECKED:MF_UNCHECKED),IDM_STARTUP,L"Εκκίνηση με τα Windows"); AppendMenuW(m,MF_STRING,IDM_ABOUT,L"Σχετικά"); AppendMenuW(m,MF_SEPARATOR,0,nullptr); AppendMenuW(m,MF_STRING,IDM_EXIT,L"Έξοδος"); POINT p{}; GetCursorPos(&p); SetForegroundWindow(gMain); UINT cmd=TrackPopupMenu(m,TPM_RIGHTBUTTON|TPM_RETURNCMD|TPM_NONOTIFY,p.x,p.y,0,gMain,nullptr); PostMessageW(gMain,WM_NULL,0,0); DestroyMenu(m); if(cmd) handleCmd(cmd);} 
bool addTray(){gTray={}; gTray.cbSize=sizeof(gTray); gTray.hWnd=gMain; gTray.uID=TRAYID; gTray.uFlags=NIF_MESSAGE|NIF_ICON|NIF_TIP; gTray.uCallbackMessage=WM_TRAY; gTray.hIcon=gIcon?gIcon:LoadIconW(nullptr,IDI_APPLICATION); wcsncpy_s(gTray.szTip,APP,_TRUNCATE); if(!Shell_NotifyIconW(NIM_ADD,&gTray)) return false; gTray.uVersion=NOTIFYICON_VERSION_4; Shell_NotifyIconW(NIM_SETVERSION,&gTray); updateTip(); return true;}
void removeTray(){if(gTray.hWnd){Shell_NotifyIconW(NIM_DELETE,&gTray); gTray={};}}
void drawPin(HDC h,const RECT& rc){int w=rc.right-rc.left,hg=rc.bottom-rc.top; HBRUSH bg=CreateSolidBrush(RGB(255,0,255)); FillRect(h,&rc,bg); DeleteObject(bg); HPEN pen=CreatePen(PS_SOLID,1,RGB(120,0,0)),oldP=(HPEN)SelectObject(h,pen); HBRUSH b1=CreateSolidBrush(RGB(220,25,25)),b2=CreateSolidBrush(RGB(25,25,25)),b3=CreateSolidBrush(RGB(55,55,55)),b4=CreateSolidBrush(RGB(170,170,170)),oldB=(HBRUSH)SelectObject(h,b1); Ellipse(h,w/2-8,2,w/2+8,18); SelectObject(h,b2); Ellipse(h,w/2-5,3,w/2+5,11); SelectObject(h,b3); RoundRect(h,w/2-2,13,w/2+2,23,2,2); SelectObject(h,b4); POINT t[3]={{w/2-4,21},{w/2+5,21},{w/2,hg-2}}; Polygon(h,t,3); SelectObject(h,oldB); SelectObject(h,oldP); DeleteObject(b4); DeleteObject(b3); DeleteObject(b2); DeleteObject(b1); DeleteObject(pen);} 
LRESULT CALLBACK markProc(HWND w,UINT m,WPARAM wp,LPARAM lp){switch(m){case WM_NCHITTEST:return HTTRANSPARENT; case WM_ERASEBKGND:return 1; case WM_PAINT:{PAINTSTRUCT ps{}; HDC h=BeginPaint(w,&ps); RECT r{}; GetClientRect(w,&r); drawPin(h,r); EndPaint(w,&ps); return 0;}} return DefWindowProcW(w,m,wp,lp);} 
LRESULT CALLBACK selProc(HWND w,UINT m,WPARAM wp,LPARAM lp){switch(m){case WM_LBUTTONDOWN:GetCursorPos(&gPick); cancelSelect(); PostMessageW(gMain,WM_PICKED,0,0); return 0; case WM_RBUTTONDOWN: cancelSelect(); return 0; case WM_KEYDOWN: if(wp==VK_ESCAPE){cancelSelect(); return 0;} break; case WM_SETCURSOR:SetCursor(LoadCursorW(nullptr,IDC_CROSS)); return TRUE; case WM_ERASEBKGND:return 1;} return DefWindowProcW(w,m,wp,lp);} 
LRESULT CALLBACK mainProc(HWND w,UINT m,WPARAM wp,LPARAM lp){switch(m){case WM_TRAY:{UINT tm=LOWORD(lp); if(tm==WM_LBUTTONUP||tm==NIN_SELECT||tm==NIN_KEYSELECT) beginSelect(); else if(tm==WM_RBUTTONUP||tm==WM_CONTEXTMENU) showMenu(); return 0;} case WM_PICKED: finishSelect(); return 0; case WM_HOTKEY: if(wp==HOTKEYID) togglePinned(GetForegroundWindow()); return 0; case WM_TIMER: if(wp==TIMID){refreshMarks(); return 0;} break; case WM_CLOSE: DestroyWindow(w); return 0; case WM_DESTROY: KillTimer(w,TIMID); cancelSelect(); UnregisterHotKey(w,HOTKEYID); unpinAll(); removeTray(); PostQuitMessage(0); return 0;} return DefWindowProcW(w,m,wp,lp);} 
bool regClasses(){WNDCLASSEXW wc{}; wc.cbSize=sizeof(wc); wc.lpfnWndProc=mainProc; wc.hInstance=gInst; wc.hIcon=gIcon; wc.hIconSm=gIcon; wc.lpszClassName=MAINCLS; if(!RegisterClassExW(&wc)) return false; WNDCLASSEXW sc{}; sc.cbSize=sizeof(sc); sc.lpfnWndProc=selProc; sc.hInstance=gInst; sc.hCursor=LoadCursorW(nullptr,IDC_CROSS); sc.hbrBackground=(HBRUSH)GetStockObject(BLACK_BRUSH); sc.lpszClassName=SELCLS; if(!RegisterClassExW(&sc)) return false; WNDCLASSEXW mc{}; mc.cbSize=sizeof(mc); mc.lpfnWndProc=markProc; mc.hInstance=gInst; mc.hCursor=LoadCursorW(nullptr,IDC_ARROW); mc.hbrBackground=(HBRUSH)GetStockObject(HOLLOW_BRUSH); mc.lpszClassName=MARKCLS; return RegisterClassExW(&mc)!=0;}
bool createWindows(){gMain=CreateWindowExW(0,MAINCLS,APP,WS_OVERLAPPED,0,0,0,0,nullptr,nullptr,gInst,nullptr); if(!gMain) return false; gSel=CreateWindowExW(WS_EX_TOPMOST|WS_EX_TOOLWINDOW|WS_EX_LAYERED,SELCLS,L"",WS_POPUP,0,0,0,0,nullptr,nullptr,gInst,nullptr); if(!gSel) return false; SetLayeredWindowAttributes(gSel,0,1,LWA_ALPHA); ShowWindow(gSel,SW_HIDE); return true;}
}

int WINAPI wWinMain(HINSTANCE h,HINSTANCE,PWSTR,int){gInst=h; SetProcessDPIAware(); gIcon=(HICON)LoadImageW(h,MAKEINTRESOURCEW(IDI_APP),IMAGE_ICON,0,0,LR_DEFAULTSIZE); HANDLE mx=CreateMutexW(nullptr,TRUE,MUTEXNAME); if(!mx) return 1; if(GetLastError()==ERROR_ALREADY_EXISTS){CloseHandle(mx); return 0;} if(!regClasses()||!createWindows()){MessageBoxW(nullptr,L"Το dwrean DeskPins δεν μπόρεσε να ξεκινήσει.",APP,MB_OK|MB_ICONERROR); if(gIcon) DestroyIcon(gIcon); CloseHandle(mx); return 1;} if(!RegisterHotKey(gMain,HOTKEYID,MOD_CONTROL|MOD_ALT|MOD_NOREPEAT,'P')) MessageBoxW(nullptr,L"Η συντόμευση Ctrl+Alt+P χρησιμοποιείται ήδη από άλλη εφαρμογή.\nΤο dwrean DeskPins θα συνεχίσει να λειτουργεί από το εικονίδιο στο system tray.",APP,MB_OK|MB_ICONWARNING); if(!addTray()){MessageBoxW(nullptr,L"Το dwrean DeskPins δεν μπόρεσε να δημιουργήσει το εικονίδιο στο tray.",APP,MB_OK|MB_ICONERROR); DestroyWindow(gMain); if(gIcon) DestroyIcon(gIcon); CloseHandle(mx); return 1;} SetTimer(gMain,TIMID,TIMMS,nullptr); MSG msg{}; while(GetMessageW(&msg,nullptr,0,0)>0){TranslateMessage(&msg); DispatchMessageW(&msg);} if(gIcon) DestroyIcon(gIcon); CloseHandle(mx); return (int)msg.wParam;}
